### ISSUE TITLE
Add Group By CorrelationId

### ISSUE THREAD

**Issue by stokerb** [Innofactor/XrmToolBox.PluginTraceViewer#35]
Would be nice to be able to group traces by the context CorrelationId to see all plugins triggered in the execution process.
This should make it easier to identify if the a plugin is triggering multiple times in the same process.

**Comment by rappen** [comment]
# Feature description

![image](https://cloud.githubusercontent.com/assets/2572253/21892870/14655e1a-d8d9-11e6-8e9e-612c443d5679.png)

* Check ``Show Correlation`` to display the correlation column in the results
  * Correlation column will show a letter (starting with ``A``) instead of the actual guid for readability
  * Correlation column will only display letters if there are more than one recors with the same id
* Hoovering over the correlation column will display the actual guid
* Right-clicking the grid when a record is selected will enable the ``Correlation`` context menu where you can
  * see the actual guid
  * add a filter for the correlation id and re-run the log query
  * select all existing log records with the same correlation id (also available using ``<CTRL>+C``)
