### ISSUE TITLE
Errors opening against certain orgs

### ISSUE THREAD

**Issue by polshgiant** [Innofactor/XrmToolBox.PluginTraceViewer#40]
When I open the trace viewer against an on-prem connection that uses current credentials, I get the following errors.  When I open the viewer against a different IFD org, I don't get the errors.

This started happening an update or two ago, but I don't recall if it was an update to the toolbox or the plugin when I started getting the errors.

1.
> **Load**
> Failed to load entities:
> The communication object, System.ServiceModel.Channels.HttpsChannelFactory`1+HttpsRequestChannel[System.ServiceModel.Channels.IRequestChannel], cannot be used for communication because it has been Aborted.

2.
> **Load**
> Failed to load messages:
> Cannot access a disposed object.
> 
> Object name: 'System.ServiceModel.Channels.ServiceChannel'.

3. (this one happens twice)

> **Load**
> Failed to load messages:
> Cannot access a disposed object.
> 
> Object name: 'System.ServiceModel.Channels.ServiceChannel'.

4.
> **Load**
> Failed to load date constraints:
> Cannot access a disposed object.
> 
> Object name: 'System.ServiceModel.Security.TransportSecurityProtocol'.

5.
> **Load**
> Failed to load date constraints:
> AggregateQueryRecordLimit exceeded. Cannot perform this operation.

**Comment by rappen** [comment]
Hi
The last (5) problem occurs when the db contains more log records than the current AggregateQueryRecord limit, which usually is 50000.
The error is "ugly", but only affects the pre-loading of filter values. It does not affect the other functionality of the tool.
However I do not know what errors 1-4 may be. Perhaps these are result of error 5, since the loading of filter constraints is done threaded at the same time.
Have you seen any issues with this organization in other tools?
